---
# tasks file for resolv
- name: "setup resolv.conf"
  action: template src=resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644
  tags: 
    - resolv
    - config

# setup local facts
- include: facts.yml
