---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian-9
    image: debian:9
  - name: ubuntu-18.04
    image: ubuntu:18.04
  - name: centos-7
    image: centos:7
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        resolv_file: /tmp/resolv.conf
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: github
verifier:
  name: testinfra
  lint:
    name: flake8
